# .circleci/config.yml for CircleCI 2.0
version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v8-dependencies-{{ checksum "package.json" }}-{{ checksum "elm-package.json" }}
          - v8-dependencies-
      - run: ./scripts/ci/ensure_libsysconfcpus.sh
      - run: npm install
      - run: ./scripts/ci/replace_elm_make.sh 1
      - run: npm test
      - save_cache:
          paths:
            - sysconfcpus
            - node_modules
            - elm-stuff
            - tests/elm-stuff
          key: v8-dependencies-{{ checksum "package.json" }}-{{ checksum "elm-package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - node8
